kind: Deployment
apiVersion: apps/v1
metadata:
  name: planning-poker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planning-poker
  template:
    metadata:
      labels:
        app: planning-poker
    spec:
      containers:
        - name: planning-poker
          image: planning-poker
          imagePullPolicy: Never
          ports:
            - containerPort: 80
      restartPolicy: Always

---

kind: Service
apiVersion: v1
metadata:
  name: planning-poker
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 32000
  selector:
    app: planning-poker
