FROM nginx:alpine

COPY ./nginx.conf /etc/nginx/conf.d/default.confg

#COPY ./backend-not-found.html /var/www/html/backend-not-found.html

#COPY ./includes/ /etc/nginx/includes/

#COPY ./ssl/ /etc/ssl/certs/nginx/