name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
      name: Checkout
      uses: actions/checkout@v3
    -  
     name: Set up Docker Buildx
     uses: docker/setup-buildx-action@v1
    - 
      if: github.event_name != 'pull_request'
      name: Log in to GHE Container Repo
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push Frontend
      uses: docker/build-push-action@v2
      with:
        context: frontend/.
        file: ./frontend/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        push: true
        tags: ghcr.io/scaled-agile-inc/pointer-frontend-12:latest
    -
      name: Build and push Backend
      uses: docker/build-push-action@v2
      with:
        context: backend/.
        file: ./backend/Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        tags: ghcr.io/scaled-agile-inc/pointer-backend-1:latest
        push: true
  
